[package]
name = "yee"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hybrid-clocks = "0.5.3"
merkletree = "0.21.0"
radix_fmt = "1.0.0"
